# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchmakerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestPlayers = channel.unary_unary(
                '/MatchmakerService/RequestPlayers',
                request_serializer=messages__pb2.Player.SerializeToString,
                response_deserializer=messages__pb2.PlayerList.FromString,
                _registered_method=True)
        self.ConfirmToMatch = channel.unary_unary(
                '/MatchmakerService/ConfirmToMatch',
                request_serializer=messages__pb2.PlayerList.SerializeToString,
                response_deserializer=messages__pb2.Status.FromString,
                _registered_method=True)


class MatchmakerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestPlayers(self, request, context):
        """retrieves a list of players considered online at the time of the rpc being received
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmToMatch(self, request, context):
        """coordinator calls this rpc to tell shards which players are in a match.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchmakerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPlayers,
                    request_deserializer=messages__pb2.Player.FromString,
                    response_serializer=messages__pb2.PlayerList.SerializeToString,
            ),
            'ConfirmToMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmToMatch,
                    request_deserializer=messages__pb2.PlayerList.FromString,
                    response_serializer=messages__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MatchmakerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MatchmakerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchmakerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchmakerService/RequestPlayers',
            messages__pb2.Player.SerializeToString,
            messages__pb2.PlayerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmToMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MatchmakerService/ConfirmToMatch',
            messages__pb2.PlayerList.SerializeToString,
            messages__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
