# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x16\n\x06Status\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\"\x18\n\x06Player\x12\x0e\n\x06values\x18\x01 \x03(\x02\" \n\nPlayerList\x12\x12\n\nplayersIds\x18\x01 \x03(\x03\x32\x63\n\x11MatchmakerService\x12&\n\x0eRequestPlayers\x12\x07.Player\x1a\x0b.PlayerList\x12&\n\x0e\x43onfirmToMatch\x12\x0b.PlayerList\x1a\x07.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=18
  _globals['_STATUS']._serialized_end=40
  _globals['_PLAYER']._serialized_start=42
  _globals['_PLAYER']._serialized_end=66
  _globals['_PLAYERLIST']._serialized_start=68
  _globals['_PLAYERLIST']._serialized_end=100
  _globals['_MATCHMAKERSERVICE']._serialized_start=102
  _globals['_MATCHMAKERSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
