# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyValueStoreStub(object):
    """Key-Value Store service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kvstore.KeyValueStore/Put',
                request_serializer=messages__pb2.PutRequest.SerializeToString,
                response_deserializer=messages__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kvstore.KeyValueStore/Get',
                request_serializer=messages__pb2.GetRequest.SerializeToString,
                response_deserializer=messages__pb2.GetResponse.FromString,
                _registered_method=True)


class KeyValueStoreServicer(object):
    """Key-Value Store service
    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=messages__pb2.PutRequest.FromString,
                    response_serializer=messages__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=messages__pb2.GetRequest.FromString,
                    response_serializer=messages__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.KeyValueStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Key-Value Store service
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KeyValueStore/Put',
            messages__pb2.PutRequest.SerializeToString,
            messages__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KeyValueStore/Get',
            messages__pb2.GetRequest.SerializeToString,
            messages__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorClientStub(object):
    """Client-coordinator service- rpcs facing clients, listening on coordinator
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/kvstore.CoordinatorClient/Login',
                request_serializer=messages__pb2.GetRequest.SerializeToString,
                response_deserializer=messages__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RequestMatch = channel.unary_unary(
                '/kvstore.CoordinatorClient/RequestMatch',
                request_serializer=messages__pb2.PutRequest.SerializeToString,
                response_deserializer=messages__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/kvstore.CoordinatorClient/Ping',
                request_serializer=messages__pb2.GetRequest.SerializeToString,
                response_deserializer=messages__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/kvstore.CoordinatorClient/Logout',
                request_serializer=messages__pb2.GetRequest.SerializeToString,
                response_deserializer=messages__pb2.GetResponse.FromString,
                _registered_method=True)


class CoordinatorClientServicer(object):
    """Client-coordinator service- rpcs facing clients, listening on coordinator
    """

    def Login(self, request, context):
        """Request key is any. Response returns a LoginResponse, which if successful, contains the attributes and id of a client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMatch(self, request, context):
        """Request key is the client's id. returns success with no message, if client was put into matchmaking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """heartbeat. Request key is client's id. returns 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """logs a client out, removing them from any queuing. Key is client's id, returns an empty string if successful.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=messages__pb2.GetRequest.FromString,
                    response_serializer=messages__pb2.LoginResponse.SerializeToString,
            ),
            'RequestMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMatch,
                    request_deserializer=messages__pb2.PutRequest.FromString,
                    response_serializer=messages__pb2.PutResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=messages__pb2.GetRequest.FromString,
                    response_serializer=messages__pb2.PingResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=messages__pb2.GetRequest.FromString,
                    response_serializer=messages__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.CoordinatorClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.CoordinatorClient', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorClient(object):
    """Client-coordinator service- rpcs facing clients, listening on coordinator
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorClient/Login',
            messages__pb2.GetRequest.SerializeToString,
            messages__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorClient/RequestMatch',
            messages__pb2.PutRequest.SerializeToString,
            messages__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorClient/Ping',
            messages__pb2.GetRequest.SerializeToString,
            messages__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorClient/Logout',
            messages__pb2.GetRequest.SerializeToString,
            messages__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServerStub(object):
    """Server-coordinator service- rpcs facing servers, listening on coordinator
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/kvstore.CoordinatorServer/Register',
                request_serializer=messages__pb2.RegisterRequest.SerializeToString,
                response_deserializer=messages__pb2.GetResponse.FromString,
                _registered_method=True)
        self.WorkloadComplete = channel.unary_unary(
                '/kvstore.CoordinatorServer/WorkloadComplete',
                request_serializer=messages__pb2.WorkloadResultRequest.SerializeToString,
                response_deserializer=messages__pb2.PutResponse.FromString,
                _registered_method=True)


class CoordinatorServerServicer(object):
    """Server-coordinator service- rpcs facing servers, listening on coordinator
    """

    def Register(self, request, context):
        """Request includes ip and port for a server, if successful response returns true and optionally, an id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkloadComplete(self, request, context):
        """Request features per-client results from a workload. Response returns success if results were received.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=messages__pb2.RegisterRequest.FromString,
                    response_serializer=messages__pb2.GetResponse.SerializeToString,
            ),
            'WorkloadComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkloadComplete,
                    request_deserializer=messages__pb2.WorkloadResultRequest.FromString,
                    response_serializer=messages__pb2.PutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.CoordinatorServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.CoordinatorServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorServer(object):
    """Server-coordinator service- rpcs facing servers, listening on coordinator
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorServer/Register',
            messages__pb2.RegisterRequest.SerializeToString,
            messages__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorkloadComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.CoordinatorServer/WorkloadComplete',
            messages__pb2.WorkloadResultRequest.SerializeToString,
            messages__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GameServerStub(object):
    """game server rpcs, dependent on the workload of gameservers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRound = channel.unary_unary(
                '/kvstore.GameServer/RequestRound',
                request_serializer=messages__pb2.GetRequest.SerializeToString,
                response_deserializer=messages__pb2.RoundResponse.FromString,
                _registered_method=True)
        self.SendResult = channel.unary_unary(
                '/kvstore.GameServer/SendResult',
                request_serializer=messages__pb2.PutRequest.SerializeToString,
                response_deserializer=messages__pb2.PutResponse.FromString,
                _registered_method=True)


class GameServerServicer(object):
    """game server rpcs, dependent on the workload of gameservers
    """

    def RequestRound(self, request, context):
        """Used to retrieve info about a new round in the workload of the server. request has client id as key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResult(self, request, context):
        """used for clients to send data in a round back to the server. key is client id, value is result client is sending.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRound': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRound,
                    request_deserializer=messages__pb2.GetRequest.FromString,
                    response_serializer=messages__pb2.RoundResponse.SerializeToString,
            ),
            'SendResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResult,
                    request_deserializer=messages__pb2.PutRequest.FromString,
                    response_serializer=messages__pb2.PutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.GameServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.GameServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameServer(object):
    """game server rpcs, dependent on the workload of gameservers
    """

    @staticmethod
    def RequestRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.GameServer/RequestRound',
            messages__pb2.GetRequest.SerializeToString,
            messages__pb2.RoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.GameServer/SendResult',
            messages__pb2.PutRequest.SerializeToString,
            messages__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
